# Render configuration for LXERA Agent Pipeline
# Updated to use gthread workers for better async compatibility
services:
  - type: web
    name: lxera-agent-pipeline
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --workers 2 --bind 0.0.0.0:$PORT --timeout 600 --worker-class gthread --threads 4 app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: GROQ_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: TAVILY_API_KEY
        sync: false
      - key: FIRECRAWL_API_KEY
        sync: false
      - key: PORT
        value: 10000
    healthCheckPath: /ping