services:
  - type: web
    name: lxera-agent-pipeline
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: OPENAI_API_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: TAVILY_API_KEY
        sync: false
      - key: FIRECRAWL_API_KEY
        sync: false
      - key: PORT
        value: 10000
    healthCheckPath: /health